### ISSUE TITLE
Measuring test coverage

### ISSUE THREAD

**Issue by azuchi** [chaintope/glueby#186]
Measure test coverage and add tests where they are lacking.

**Comment by rantan** [comment]
カバレッジを計測しこの Issue に結果をまとめる。テストの追加については個別に Issue を作る。

**Comment by Yamaguchi** [comment]
![Code-coverage-for-Glueby](https://github.com/chaintope/glueby/assets/220267/4fa95c45-db2a-4b40-9382-841d74bef283)

**Comment by Yamaguchi** [comment]
```1735 relevant lines, 1624 lines covered and 111 lines missed. ( 93.6% )```
