### ISSUE TITLE
Error `Could not find table 'glueby_timestamps'`

### ISSUE THREAD

**Issue by nakajo2011** [chaintope/glueby#77]
# Description
### Precondition
I use active record wallet, and I do not use timestamp contract.
so, I generated two migrations bellow:
```
 $ rails g glueby:contract:block_syncer
 $ rails g glueby:contract:wallet_adapter
```

### What happened
I run block_syncer task.
```
 rails glueby:contract:block_syncer:start
```

then, I got those error message:
```
[Deprecated] glueby:contract:block_syncer:start is deprecated. Use 'glueby:block_syncer:start'
rails aborted!
ActiveRecord::StatementInvalid: Could not find table 'glueby_timestamps'
/myapp/bin/rails:5:in `<top (required)>'
/myapp/bin/spring:10:in `block in <top (required)>'
/myapp/bin/spring:7:in `<top (required)>'
Tasks: TOP => glueby:contract:block_syncer:start
(See full trace by running task with --trace)
```

BlockSyncer always needs glueby_timestamps table.
But, I do not use Timestamp Contract. so I want not to create that table.

# Expected Work
I wanna select to sync timestamp or not in `config/initializers/glueby.rb`. like this:
```
sync_timestamp = true
```

# Environment
Ruby: v3.0.1
Rails: v6.1.4
Glueby: revision: 7b345102d153623cf694d0cf051d3b1c5fb0a820 (install from github)

**Comment by Yamaguchi** [comment]
I think `BlockSyncer#register_syncer` method should be called for Timestamp if and only if timestamps table has been created already.

https://github.com/chaintope/glueby/blob/7b345102d153623cf694d0cf051d3b1c5fb0a820/lib/glueby/railtie.rb#L4
