### ISSUE TITLE
How to connect Contract::Timestamp and AR::Timestamp?

### ISSUE THREAD

**Issue by nakajo2011** [chaintope/glueby#81]
# Description
How to use Gleuby::AR::Timestamp?

I implemented following code for connect Glueby::Contract::Timestamp and Glueby::AR::Timestamp.

```
    timestamp = Glueby::Contract::Timestamp.new(wallet: wallet, content: self.message)
    # save in active record
    ar_t = Glueby::Contract::AR::Timestamp.new(wallet_id: wallet.id, content: self.message)
    tx = timestamp.save!
    ar_t.txid = tx.txid
    ar_t.save!
    ar_t.unconfirmed! # statusをunconfirmedに更新
```

It is not communicativity. Looks like individual working. 

# Expected Work
```
    timestamp = Glueby::Contract::Timestamp.new(wallet: wallet, content: self.message, activerecord: true)
    tx = timestamp.save! # save to active record in same time.
```

**Comment by Yamaguchi** [comment]
see https://github.com/chaintope/glueby#rails-support

You should use glueby:contract:timestamp:create and glueby:block_syncer:start.

**Comment by Yamaguchi** [comment]
I think README.md should be improved to be more readable....
